- name: Check pre-requisites
  fail:
    msg: "Environment variable {{item}} not set. Please declare an environment variable with an appropriate value for the sample to work."
  when: item not in ansible_env
  with_items:
    - "SAMPLE_COMPARTMENT_OCID"
    - "SAMPLE_IMAGE_OCID"

# find the availability domain that is Always Free eligible in this tenancy
- name: List availbility domains
  oci_ad_facts:
    compartment_id: "{{ instance_compartment }}"
  register: result

- set_fact:
    availability_domains: "{{ result.availability_domains }}"

- debug:
    msg: "{{ availability_domains }}"

- name: List shapes in first AD
  oci_shape_facts:
    compartment_id: "{{ instance_compartment }}"
    image_id: "{{ instance_image }}"
    availability_domain: "{{ availability_domains[0].name }}"
  register: result
  when: availability_domains | length > 0
